[[redirects]]
  from = "/*"
  to = "https://monacodelisa.dev"
  status = 301
  force = true

[[redirects]]
  from = "https://monacodelisa.com/*"
  to = "https://monacodelisa.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.monacodelisa.com/*"
  to = "https://blog.esthersoftware.dev/:splat"
  status = 301
  force = true