[build]
  base = ""
  command = "npm run build"
  publish = "dist/browser"

# Redirect for monacodelisa.com to monacodelisa.dev
[[redirects]]
  from = "https://monacodelisa.com/*"
  to = "https://monacodelisa.dev/:splat"
  status = 301
  force = true

# Redirect for blog.monacodelisa.com to monacodelisa.dev
[[redirects]]
  from = "https://blog.monacodelisa.com/*"
  to = "https://monacodelisa.dev/:splat"
  status = 301
  force = true

# SPA Redirect Rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
